### ISSUE TITLE
Issue of installation on Mac maverick

### ISSUE THREAD

**Issue by kwyip** [cgranade/python-quaec#7]
I encountered an error in installation in python-quaec. 
It is: ImportError: No module named 'singletons'

I also tried PyPl but the same issue happened.

I am using mac and python3.4
<img width="571" alt="screen shot 2016-05-07 at 12 17 23 pm" src="https://cloud.githubusercontent.com/assets/7807159/15094047/c41180ec-144d-11e6-8dd6-1aba0dafe6a9.png">
<img width="1060" alt="screen shot 2016-05-07 at 12 18 27 pm" src="https://cloud.githubusercontent.com/assets/7807159/15094053/dc3be194-144d-11e6-842e-ad54ed2cdc99.png">

**Comment by bcriger** [comment]
I don't immediately know what's wrong, but I can say this:
 - `singletons` is the first submodule imported, so no submodule is being successfully imported
 - the `src` directory is added to the path before setup (see [here](https://github.com/cgranade/python-quaec/blob/master/setup.py#L5))
 - `setup.py` works fine on my computer, so I'll have to ask you to do some more tests. 

For instance, if you `cd` into the `src` directory, can you import these modules in ipython?
Can you install other libraries, or is there some global problem?
Can you run line 5 of `setup.py` and see if it changes your path appropriately?

Good luck, 

Ben

**Comment by kwyip** [comment]
I found that the issue is just switching back to use python2.7. How can I forget? Thank you for your help.
